/* Generated by powerful Codeforces Tool
 * Author: czhang
 * Time: 2021-03-02 23:07:47
**/

#include <bits/stdc++.h>

using namespace std;
typedef long long ll;

void solve() {
    int a, b, k;
    cin>>a>>b>>k;
    int l = max(k, a) + 1, r = min(1 + a + k, a + b) - 1;
    if (k == 0) {
        cout<<"Yes"<<endl;
        for (int i = 0; i < a + b; ++i) {
            if (i > 0 && i <= a) {
                cout<<0;
            } else {
                cout<<1;
            }
        }
        cout<<endl;

        for (int i = 0; i < a + b; ++i) {
            if (i > 0 && i <= a) {
                cout<<0;
            } else {
                cout<<1;
            }
        }
        cout<<endl;
    } else if (l <= r) {
        cout<<"Yes"<<endl;
        for (int i = 0; i < a + b; ++i) {
            if (i > 0 && i <= a) {
                cout<<(i == (r - k));
            } else {
                cout<<(i != r);
            }
        }
        cout<<endl;

        for (int i = 0; i < a + b; ++i) {
            if (i > 0 && i <= a) {
                cout<<0;
            } else {
                cout<<1;
            }
        }
        cout<<endl;
    } else {
        cout<<"No"<<endl;
    }
}

int main() {
    ios_base::sync_with_stdio(0);
    cin.tie(0); cout.tie(0);
    int tc = 1;
    // cin>>tc;
    for (int i = 0; i < tc; ++i) {
        solve();
    }
    return 0;
}
