/* Generated by powerful Codeforces Tool
 * Author: czhang
 * Time: 2021-03-01 23:22:35
**/

#include <bits/stdc++.h>
#include <stack>

using namespace std;
typedef long long ll;

void solve() {
    int n;
    int arr[100004];
    stack<int> s;
    
    cin>>n;
    for (int i = 0; i < n; ++i) {
        cin>>arr[i];
        if (s.empty() || arr[s.top()] < arr[i]) {
            s.push(i);
        }
    }

    while (s.size()) {
        int last = s.top();
        for (int i = last; i < n; ++i) {
            cout<<arr[i]<<' ';
        }
        n = last;
        s.pop();
    }
    cout<<endl;
}

int main() {
    ios_base::sync_with_stdio(0);
    cin.tie(0); cout.tie(0);
    int tc = 1;
    cin>>tc;
    for (int i = 0; i < tc; ++i) {
        solve();
    }
    return 0;
}
