/* Generated by powerful Codeforces Tool
 * Author: czhang
 * Time: 2021-03-09 21:16:21
**/

#include <bits/stdc++.h>
#include <valarray>

using namespace std;
typedef long long ll;

void solve() {
    int n, k;
    cin>>n>>k;
    valarray<bool> arr(n+1);
    for (int i = 0; i < n+1; ++i) {
        arr[i] = true;
    }
    arr[k] = false;
    for (int i = 1; i * 2 < k; ++i) {
        if (arr[i] && arr[k - i]) {
            arr[i] = false;
        }
    }
    int c = 0;
    for (int i = 1; i <= n; ++i) {
        if (arr[i]) ++c;
    }
    cout<<c<<endl;
    if (c) {
        for (int i = 1; i <= n; ++i) {
            if (arr[i]) cout<<i<<' ';
        }
        cout<<endl;
    }
}

int main() {
    ios_base::sync_with_stdio(0);
    cin.tie(0); cout.tie(0);
    int tc = 1;
    cin>>tc;
    for (int i = 0; i < tc; ++i) {
        solve();
    }
    return 0;
}
