/* Generated by powerful Codeforces Tool
 * Author: czhang
 * Time: 2021-03-18 00:31:25
**/

#include <bits/stdc++.h>

using namespace std;
typedef long long ll;

void solve() {
    ll n, k;
    cin>>n>>k;
    if (n & 1) {
        ll x = (n - 1) / 2;
        cout<<1<<' '<<x<<' '<<x<<endl;
    } else if (n % 4 == 0) {
        ll x = n / 4;
        cout<<x*2<<' '<<x<<' '<<x<<endl;
    } else {
        ll x = (n/2 - 1) / 2;
        cout<<2<<' '<<x*2<<' '<<x*2<<endl;
    }
}

int main() {
    ios_base::sync_with_stdio(0);
    cin.tie(0); cout.tie(0);
    int tc = 1;
    cin>>tc;
    for (int i = 0; i < tc; ++i) {
        solve();
    }
    return 0;
}
