/* Generated by powerful Codeforces Tool
 * Author: czhang
 * Time: 2021-03-17 22:37:14
**/

#include <bits/stdc++.h>

using namespace std;
typedef long long ll;

string &&add(string &s) {
    int i = s.size() - 1;
    while (s[i] == '1') {
        s[i--] = '0';
    }
    s[i] = '1';
    return move(s);
}

void solve() {
    int n;
    string l, r;
    cin>>n;
    cin>>l>>r;
    if (l == r) {
        cout<<r<<endl;
    } else if (l[0] != r[0]) {
        for (int i = 0; i < n; ++i) {
            cout<<1;
        }
        cout<<endl;
    } else if (add(l) == r || r.back() == '1') {
        cout<<r<<endl;
    } else {
        cout<<add(r)<<endl;
    }
}

int main() {
    ios_base::sync_with_stdio(0);
    cin.tie(0); cout.tie(0);
    int tc = 1;
    // cin>>tc;
    for (int i = 0; i < tc; ++i) {
        solve();
    }
    return 0;
}
